### ISSUE TITLE
Exclude 500% or more transactions

### ISSUE THREAD

**Issue by talos** [provolot/landscapes-of-profit#1]
If a sale was for more than 5x purchase price, exclude it as an outlier.

**Comment by clhenrick** [comment]
@talos so `SELECT * FROM nyc_flips`where ratiopricediff < 5;` ?

**Comment by dantaeyoung** [comment]
@talos: Outliers because they may indicate an error in the data, or outliers because it's unrepresentative of a general phenomena?

**Comment by talos** [comment]
I don't think we can speak of a general phenomenon, and I don't think we can say for sure that they are errors in the data.  Considering the time and resources (and honestly, the precision with which we're working) it is just easier to eliminate numbers that are likely outliers.

**Comment by clhenrick** [comment]
So @talos @provolot  it's okay for now?

**Comment by dantaeyoung** [comment]
@clhenrick What @talos says makes total sense - so yes, okay for now / good thing we implemented this

**Comment by clhenrick** [comment]
:+1:
