### ISSUE TITLE
Exclude transactions < $100K increase

### ISSUE THREAD

**Issue by talos** [provolot/landscapes-of-profit#2]
If the sale was for less than $100K more than the purchase, exclude it as the cost of a gut reno for a cheaper property could easily hit this.  Think of a property purchased for $180K and sold for $275K.  This is more than a 50% increase, but a gut reno could eat up a lot of the difference and leave the investor with just a reasonable return.

**Comment by clhenrick** [comment]
@talos so `SELECT * FROM nyc_flips WHERE (after_document_amt - before_document_amt) > 100000` ?

**Comment by talos** [comment]
Looks right to me, you got the carrot flipped in this comment but correct in the code.

**Comment by clhenrick** [comment]
Awesome, thanks @talos I just fixed it in the comment as well.
